In [2]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

Using TensorFlow backend.


In [3]:
data = pd.read_csv('mnist.csv')

In [4]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [5]:
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 220, 179,   6,   0,   0,   0,   0,
          0,   0,   0,   0,   9,  77,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [6]:
#Storing Pixel array in form length width and channel in df_x
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

#Storing the labels in y
y = data.iloc[:,0].values

In [7]:
#Converting labels to categorical features

df_y = keras.utils.to_categorical(y,num_classes=10)

In [8]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [9]:
#lables
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [10]:
#categorical labels
df_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [11]:
df_x.shape

(42000, 28, 28, 1)

In [12]:
#test train split

x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [13]:
#CNN model
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [14]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total para

In [16]:
#fitting it with just 100 images for testing 

model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10)

Train on 33600 samples, validate on 8400 samples
Epoch 1/10
33600/33600 [==============================] - 15s 461us/step - loss: 4.0566 - acc: 0.7433 - val_loss: 3.2762 - val_acc: 0.7932
Epoch 2/10
33600/33600 [==============================] - 16s 462us/step - loss: 3.1291 - acc: 0.8014 - val_loss: 2.7191 - val_acc: 0.8285
Epoch 3/10
33600/33600 [==============================] - 15s 460us/step - loss: 2.8155 - acc: 0.8217 - val_loss: 2.5799 - val_acc: 0.8381
Epoch 4/10
33600/33600 [==============================] - 15s 461us/step - loss: 2.6414 - acc: 0.8334 - val_loss: 2.4354 - val_acc: 0.8465
Epoch 5/10
33600/33600 [==============================] - 16s 466us/step - loss: 2.5449 - acc: 0.8397 - val_loss: 2.4126 - val_acc: 0.8481
Epoch 6/10
33600/33600 [==============================] - 16s 463us/step - loss: 2.4876 - acc: 0.8430 - val_loss: 2.2822 - val_acc: 0.8564
Epoch 7/10
33600/33600 [==============================] - 16s 487us/step - loss: 2.3688 - acc: 0.8511 - val_loss: 2.4

In [17]:
model.evaluate(x_test,y_test)

8400/8400 [==============================] - 1s 138us/step


[0.8020885715778353, 0.9489285714285715]