In [1]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
data=pd.read_csv('mnist.csv')

In [3]:
df_x=data.iloc[:,1:]
df_y=data.iloc[:,0]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [5]:
nn=MLPClassifier(activation='logistic',solver='sgd',hidden_layer_sizes=(10,15),random_state=1)

In [6]:
nn.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [7]:
pred=nn.predict(x_test)

In [8]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, pred))

0.8386904761904762


In [9]:
print(metrics.confusion_matrix(y_test, pred))

[[791   0   5   8   2  19   5   2   1   1]
 [  2 872   6  10   3   0   0   8   5   1]
 [ 26  28 692  52   4  12  17   5   5   2]
 [  5   9  51 710   1  13   2  29  23   8]
 [  2   2   2   0 633  10  14   2   3  93]
 [ 31   3  13  29  15 436  31   5 171  19]
 [ 16   8   7   0  11  16 796   0   4   0]
 [  4  25   6  11  12   1   0 794   0  45]
 [  2  17  10  51  25 105  15   5 546  27]
 [  4   0   0  10  39  15   0  36  13 775]]


In [10]:
nn=MLPClassifier(activation='logistic',solver='sgd',hidden_layer_sizes=(45,90),random_state=1)

In [11]:
nn.fit(x_train,y_train)

C:\Users\berk\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(45, 90), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [12]:
pred=nn.predict(x_test)

In [13]:
print(metrics.accuracy_score(y_test, pred))

0.9345238095238095


In [14]:
print(metrics.confusion_matrix(y_test, pred))

[[809   0   6   3   1   4   7   1   3   0]
 [  0 880   5   7   1   2   0   6   6   0]
 [  7   5 782  13   4   2  10   7  11   2]
 [  3   1  28 760   0  28   2  12   8   9]
 [  4   3   1   0 720   2   9   1   4  17]
 [ 13   5   7  22   2 667  13   1  16   7]
 [ 11   3   5   0   6   5 821   1   6   0]
 [  9   8  13   3   4   0   0 847   0  14]
 [  3  11   5  15   2  14   6   2 739   6]
 [  8   1   4  11  12   8   0  15   8 825]]
