In [1]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
data=pd.read_csv('mnist.csv')

In [3]:
df_x=data.iloc[:,1:]
df_y=data.iloc[:,0]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [5]:
per=Perceptron()

In [6]:
per.fit(x_train,y_train)

C:\Users\berk\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
      fit_intercept=True, max_iter=None, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [7]:
pred=per.predict(x_test)

In [8]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, pred))

0.86


In [9]:
print(metrics.confusion_matrix(y_test, pred))

[[814   1   2   2   3   2   6   0   4   0]
 [  0 896   4   2   1   3   0   1   0   0]
 [  5  38 714  11   6   8  10  12  35   4]
 [  5  27  38 689   0  15   1  12  56   8]
 [  3  20  15   3 667   2   4   2  17  28]
 [ 11  21  11  50  18 572   5   0  50  15]
 [ 13  15  17   0  13  20 774   0   6   0]
 [  5  23  23   2  11   2   1 796   4  31]
 [  4  90  11  26   1  15   2   2 646   6]
 [  5  26   8  16  61   8   0  54  58 656]]
