In [1]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
data=pd.read_csv('mnist.csv')

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [4]:
df_x=data.iloc[:,1:]
df_y=data.iloc[:,0]
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [5]:
x_train.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
32576       0       0       0       0       0       0       0       0       0   
34735       0       0       0       0       0       0       0       0       0   
3476        0       0       0       0       0       0       0       0       0   
27750       0       0       0       0       0       0       0       0       0   
16211       0       0       0       0       0       0       0       0       0   

       pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
32576       0    ...            0         0         0         0         0   
34735       0    ...            0         0         0         0         0   
3476        0    ...            0         0         0         0         0   
27750       0    ...            0         0         0         0         0   
16211       0    ...            0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
32576         0         0         0         0         0  
34735         0         0         0         0         0  
3476          0         0         0         0         0  
27750         0         0         0         0         0  
16211         0         0         0         0         0  

[5 rows x 784 columns]

In [6]:
y_train.head()

32576    5
34735    0
3476     3
27750    0
16211    3
Name: label, dtype: int64

In [7]:
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [8]:
pred=rf.predict(x_test)

In [9]:
pred

array([0, 4, 0, ..., 0, 3, 1], dtype=int64)

In [10]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, pred))

0.9616666666666667


In [11]:
print(metrics.confusion_matrix(y_test, pred))

[[826   0   1   0   0   1   3   0   3   0]
 [  0 889   6   4   2   0   0   4   2   0]
 [  4   4 814   3   6   0   3   4   3   2]
 [  2   1  22 801   0   8   1   7   6   3]
 [  2   1   1   1 739   1   3   0   0  13]
 [  3   2   0  16   1 713   7   0   6   5]
 [  4   2   1   0   3   1 844   0   3   0]
 [  3   5  13   2   1   0   0 855   4  15]
 [  1   7   4   7   6   7   1   2 759   9]
 [  5   0   4  15  14   3   0   3  10 838]]
